445 EDGES 
307 STATIONS

In [12]:
import numpy as np
import tensorflow as tf


x = np.ones(shape=(1, 307, 307))  
y = np.ones(shape=(1, 307, 307)) 

print(x)

model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(307, 307)),  
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(307 * 307, activation="relu"), 
    tf.keras.layers.Reshape((307, 307, 1)) 
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Fit the model
model.fit(x, y, epochs=5)


[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 838ms/step - loss: 0.9722
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 5.4287
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.6192
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.9936
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 0.9992
